development:
  adapter: postgresql
  database: student_map
  pool: 5
  timeout: 5000
  username: rorybudnick
  host: localhost

test:
  adapter: postgresql
  database: student_map_test
  pool: 5
  timeout: 5000
  username: rorybudnick
  host: localhost

production:
  adapter: postgresql
  database: student_map_production
  pool: 5
  timeout: 5000
  username: rorybudnick
  host: localhost
